### ISSUE TITLE
Problem passing travis

### ISSUE THREAD

**Issue by JMMaronge** [ANTsX/ANTsRCore#69]
I'm getting this error when running travis:

```
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
Calls: install_missing_remote_deps ... remote_package_deps -> get_dep_table -> lapply -> FUN
Execution halted
The command "install_missing_remote_deps_all ${ants_user}/ANTsRCore ${ants_user}/ANTsR" failed and exited with 1 during .
```
The travis build is [here](https://travis-ci.org/JMMaronge/medals/builds/453136766).

Before the most recent commit to ANTsRCore, I had the same .travis file, but was able to install ANTsRCore, build is [here](https://travis-ci.org/JMMaronge/medals/builds/452645691).

My current .travis.yml file is:

```
 language: r
warnings_are_errors: true
sudo: false
cache: packages
use_bioc: true
bioc_required: true
r: release

os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"

before_install:
  - export PROJ_DIR=`basename $PWD`    
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - cat DESCRIPTION
  - remove_neuroc_packages 
  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
  # does all the clang exports
  - x=`export_clang_cxx`; eval ${x}
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
  - clang_cxx  
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
  - export ants_user=ANTsX
  - install_missing_remote_deps_all stnava/ITKR
  - install_missing_remote_deps_all ${ants_user}/ANTsRCore ${ants_user}/ANTsR
  - echo "Done Installing Missing Deps"
  - gh_binary_install stnava/ITKR
  - gh_binary_install ${ants_user}/ANTsRCore
  - gh_binary_install ${ants_user}/ANTsR  
  - cat DESCRIPTION
  - install_remotes_no_dep
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
```
Any suggestions?
